"""Verify the dependency-direction contracts declared in .importlinter (AC-G1).

Runs the installed ``lint-imports`` console script (see .venv/bin) as a subprocess
against the repo root, so this test exercises the same entry point a developer or
CI would run via ``uv run lint-imports``.
"""

import os
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


def _lint_imports_command() -> list[str]:
    """Locate the ``lint-imports`` console script installed next to sys.executable.

    ``importlinter.cli`` has no ``__main__`` entry point, so ``python -m`` is not
    usable here; the console script generated by the package's entry point is.
    """
    script = Path(sys.executable).parent / "lint-imports"
    if script.is_file():
        return [str(script)]
    # Fall back to relying on PATH (e.g. non-POSIX layouts).
    return ["lint-imports"]


def test_lint_imports_passes() -> None:
    result = subprocess.run(
        [*_lint_imports_command(), "--no-cache"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        env={**os.environ},
    )

    assert result.returncode == 0, (
        "lint-imports reported a dependency-direction violation "
        f"(exit {result.returncode}):\n{result.stdout}\n{result.stderr}"
    )


def test_sdk_imports_no_app() -> None:
    """``harness`` and ``domains`` never name an app package (ADR-0018 s19)."""
    import ast

    offending: list[str] = []
    for root in ("harness", "domains"):
        for path in (REPO_ROOT / root).rglob("*.py"):
            for node in ast.walk(ast.parse(path.read_text(encoding="utf-8"))):
                names = (
                    [a.name for a in node.names]
                    if isinstance(node, ast.Import)
                    else [node.module or ""]
                    if isinstance(node, ast.ImportFrom)
                    else []
                )
                offending += [
                    f"{path.relative_to(REPO_ROOT)}: {n}"
                    for n in names
                    if n.split(".")[0] in {"apps", "swe"}
                ]
    assert not offending, offending
