"""Verify the dependency-direction contracts declared in .importlinter (AC-G1).

Runs the installed ``lint-imports`` console script (see .venv/bin) as a subprocess
against the repo root, so this test exercises the same entry point a developer or
CI would run via ``uv run lint-imports``.
"""

import os
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


def _lint_imports_command() -> list[str]:
    """Locate the ``lint-imports`` console script installed next to sys.executable.

    ``importlinter.cli`` has no ``__main__`` entry point, so ``python -m`` is not
    usable here; the console script generated by the package's entry point is.
    """
    script = Path(sys.executable).parent / "lint-imports"
    if script.is_file():
        return [str(script)]
    # Fall back to relying on PATH (e.g. non-POSIX layouts).
    return ["lint-imports"]


def test_lint_imports_passes() -> None:
    result = subprocess.run(
        [*_lint_imports_command(), "--no-cache"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        env={**os.environ},
    )

    assert result.returncode == 0, (
        "lint-imports reported a dependency-direction violation "
        f"(exit {result.returncode}):\n{result.stdout}\n{result.stderr}"
    )
